version: "3.7"

services:
  app:
    container_name: plantala-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  media-data:
    container_name: plantala-media-data
    build:
      context: medienstationAsAService
      dockerfile: Dockerfile
    volumes:
      - ./public/images:/mediaData
    command: -p /mediaData/input /mediaData
