version: '3.7'

services:
  plantala-app:
    container_name: plantala-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  plantala-media:
    container_name: plantala-media
    build:
      context: medienstationAsAService
      dockerfile: Dockerfile
    volumes:
      - ./public/images:/media
    command: -p /media/input /media/
